-- ══════════════════════════════════════════════════════════════════════════
-- DEPRECATED — DO NOT RUN
--
-- This migration was an earlier design for the attendance feature
-- where shifts were stored per-week (week_start_date + per-day
-- start/end times). The actual implementation evolved to per-day
-- shift rows (shift_date), and the live database was set up via
-- a different path (manual schema work in Supabase UI / a migration
-- file that's no longer in the repo).
--
-- The tables this file references — employee_shifts,
-- attendance_violations, attendance_eval_deductions — already exist
-- in the production database with their working schemas. Re-running
-- the original CREATE TABLE statements would do nothing (IF NOT
-- EXISTS skips them), but the indexes at the bottom of the original
-- file referenced columns (week_start_date) that don't exist in the
-- live schema, so the migration failed mid-way every time.
--
-- This file is now a no-op so the runner can record it as APPLIED
-- and stop showing it as FAILED. The actual tables continue to work
-- exactly as before — nothing in production changes.
--
-- If you ever need to recreate the attendance schema from scratch,
-- check the live DB schema in Supabase Studio and write a fresh
-- migration there.
-- ══════════════════════════════════════════════════════════════════════════

-- No-op marker. Postgres treats this as a successful empty statement.
select 1 as deprecated_migration_skipped;
